theme:
  name: "tokyo-night"
  styleOverrides:
    primary: "#7aa2f7" # голубой (акцент)
    secondary: "#bb9af7" # сиреневый
    error: "#f7768e" # красно-розовый
    inactive: "#565f89" # серый для неактивных элементов
    success: "#9ece6a" # зеленый
    warning: "#e0af68" # желто-оранжевый
  chromaStyleOverrides:
    # Общие
    text: "#c0caf5" # основной текст
    bg: "#1a1b26" # фон
    # Синтаксис
    kc: "#7dcfff bold" # ключи / идентификаторы
    kn: "#9d7cd8 bold" # ключевые слова (фиолетовые)
    kp: "#bb9af7" # псевдоключевые слова
    kr: "#bb9af7 bold" # return/if/else/for
    kt: "#2ac3de" # типы
    n: "#c0caf5" # имена
    nb: "#7aa2f7" # встроенные имена
    no: "#ff9e64" # константы
    mi: "#f7768e" # числа
    mf: "#f7768e" # числа с плавающей точкой
    s: "#e0af68" # строки
    sc: "#e0af68 italic" # символы
    sd: "#565f89 italic" # docstring
    sh: "#e0af68 bold" # строковые заголовки
    sr: "#73daca" # regexp
    si: "#2ac3de" # спецстроки
    se: "#f7768e bold" # escape-последовательности
    # Комментарии и аннотации
    cm: "#565f89 italic" # комментарии
    cp: "#565f89" # препроцессор
    c1: "#565f89 italic" # однострочные комментарии
    cs: "#565f89 italic" # спецкомментарии
    # Разное
    m: "#f7768e" # литералы (числа)
    o: "#89ddff" # операторы
    ow: "#89ddff bold" # ключевые операторы (and/or/not/in)
    # Атрибуты и теги
    nt: "#7aa2f7" # теги
    na: "#9ece6a" # атрибуты
    nd: "#7dcfff" # декораторы
    ni: "#bb9af7" # инфо/имена
    ne: "#f7768e bold" # исключения
    nf: "#7aa2f7 bold" # функции
    nx: "#c0caf5" # прочие идентификаторы
    nl: "#bb9af7" # labels

