#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

"$SCRIPT_DIR/main.sh"

yay -S --noconfirm --needed \
  abook \
  amazing-qr \
  android-studio \
  anydesk-bin \
  bagels \
  balena-etcher \
  basalt \
  bluetuith-bin \
  bombadillo-git \
  brogue-ce \
  brows \
  calcure \
  carbonyl \
  cbonsai \
  checkersland \
  clipse \
  cryptpad \
  cursor-cli \
  dblab \
  durdraw \
  envx \
  fawkes-bin \
  freetube-bin \
  fzf-make \
  glicol-cli \
  gobang-bin \
  hellwal \
  hokr-git \
  iamb-git \
  jqp-bin \
  kabmat \
  kumir2-git \
  lazyjournal \
  lazysql \
  lazyssh-bin \
  libtd-git \
  mmtui-bin \
  nsnake \
  nudoku \
  nyaa \
  obfs4proxy \
  otter-launcher \
  patat-bin \
  pokete-git \
  posting \
  puffin \
  rmtrash \
  rofi-bluetooth-git \
  rofi-greenclip \
  rudesktop \
  rustdesk-bin \
  rustnet \
  s-tui-git \
  sc-im \
  scooter \
  scope-tui \
  slides \
  speedread-git \
  sshm-bin \
  systemd-manager-tui \
  sysz \
  tinytetris \
  ttyplot \
  vex-tui-bin \
  via-appimage \
  vial-appimage \
  visualvault-bin \
  warpd \
  watchman-bin \
  wifitui-bin \
  woeusb \
  xautolock \
  xkblayout-state-git \
  yandex-disk \
  ytsurf
