theme = "Default"
default_source = "Nyaa"
timeout = 30
scroll_padding = 3
cursor_padding = 4
save_config_on_change = true
hot_reload_config = true

[client]

[source]

# # ...
# download_client = "qBittorrent"
# # ...
#
# [client.qBittorrent]
# base_url = "http://localhost:8080" # required
# username = "admin" # optional
# password = "adminadmin" # optional
# password_file = "/path/to/password.txt" # optional
# use_magnet = true # optional, will be true by default
# savepath = "~/Downloads/" # all optional with no default here and below...
# category = "Category Name"
# tags = [ # must not contain commas in any of the tags
#   "Tag one",
#   "Tag two",
# ]
# skip_checking = false
# paused = false
# create_root_folder = true
# up_limit = -1 # measured in Bytes/Sec
# dl_limit = -1 # measured in Bytes/Sec
# ratio_limit = 0.5
# seeding_time_limit = -1 # only works if auto_tmm is false, measured in minutes
# auto_tmm = false
# sequential_download = true
# prioritize_first_last_pieces = true
