[/]
current-settings-page=2
layout='/usr/share/onboard/layouts/Phone.onboard'
schema-version='2.3'
start-minimized=true
system-theme-associations={'HighContrast': 'HighContrast', 'HighContrastInverse': 'HighContrastInverse', 'LowContrast': 'LowContrast', 'ContrastHighInverse': 'HighContrastInverse', 'Default': '', 'Arc-Dark': '/usr/share/onboard/themes/Nightshade.theme'}
theme='/usr/share/onboard/themes/Nightshade.theme'
use-system-defaults=false

[icon-palette]
in-use=false

[keyboard]
audio-feedback-enabled=false
sticky-key-behavior={'all': 'dblclick'}
touch-feedback-enabled=true

[scanner]
enabled=false

[theme-settings]
background-gradient=0.0
color-scheme='/usr/share/onboard/themes/Charcoal.colors'
key-fill-gradient=8.0
key-gradient-direction=-3.0
key-label-font=''
key-shadow-size=0.0
key-shadow-strength=0.0
key-size=94.0
key-stroke-gradient=8.0
key-stroke-width=0.0
key-style='gradient'
roundrect-radius=20.0

[typing-assistance]
auto-capitalization=false

[typing-assistance/word-suggestions]
enabled=false

[window]
background-transparency=0.0
docking-enabled=true
docking-shrink-workarea=true
enable-inactive-transparency=false
force-to-top=false
transparency=0.0
transparent-background=false
window-decoration=false
window-state-sticky=true

[window/landscape]
dock-expand=true
height=210
x=608
y=435

[window/portrait]
dock-expand=true
