#!/usr/bin/env bash

yay -S --noconfirm --needed \
  anydesk-bin \
  balena-etcher \
  bitchat-tui \
  blobdrop-git \
  bluetuith-bin \
  brogue-ce \
  brows \
  cbonsai \
  checkersland \
  cruise \
  crush-bin \
  dblab \
  downloader-cli \
  durdraw \
  dysk \
  fish-done \
  gobang-bin \
  hellwal \
  jqp-bin \
  koreader-appimage \
  lazyjournal \
  lazysql \
  lazyssh-bin \
  linutil \
  mmtui-bin \
  nekoray-bin \
  nsnake \
  nudoku \
  obfs4proxy \
  onlyoffice-bin \
  opencode-bin \
  pandoc-bin \
  pantum-driver \
  pokete-git \
  portproton \
  posting \
  puffin \
  rofi-bluetooth-git \
  rofi-greenclip \
  rudesktop \
  sc-im \
  speedread-git \
  sysz \
  telegram-tg \
  tinytetris \
  torbrowser-launcher \
  ttf-ms-fonts \
  ventoy-bin \
  whatsapp-linux-desktop \
  xautolock \
  xkblayout-state-git \
  yandex-browser \
  yandex-disk \
  yandex-music \
  yazi-git \
  ytsurf
