#!/usr/bin/env bash

yay -S --noconfirm --needed \
  abook \
  anydesk-bin \
  bagels \
  balena-etcher \
  basalt \
  bitchat-tui \
  blobdrop-git \
  bluetuith-bin \
  brogue-ce \
  brows \
  calcure \
  cbonsai \
  checkersland \
  clipse \
  cruise \
  crush-bin \
  dblab \
  downloader-cli \
  durdraw \
  fish-done \
  gobang-bin \
  hellwal \
  jqp-bin \
  kabmat \
  koreader-appimage \
  lazyjournal \
  lazysql \
  lazyssh-bin \
  linutil \
  mmtui-bin \
  nekoray-bin \
  nemu \
  nsnake \
  nudoku \
  obfs4proxy \
  onlyoffice-bin \
  opencode-bin \
  pantum-driver \
  patat-bin \
  pokete-git \
  portproton \
  posting \
  puffin \
  rofi-bluetooth-git \
  rofi-greenclip \
  rudesktop \
  sc-im \
  slides \
  speedread-git \
  sshm-bin \
  sysz \
  telegram-tg \
  thokr-git \
  tinytetris \
  ttf-ms-fonts \
  ttyplot \
  ventoy-bin \
  whatsapp-linux-desktop \
  wifitui-bin \
  woeusb \
  xautolock \
  xkblayout-state-git \
  yandex-browser \
  yandex-disk \
  yandex-music \
  ytsurf
