remote_id = '56540838'
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
remote-menubar-drag-left = '0.0'
remote-menubar-drag-right = '1.0'

[ui_flutter]
peer-sorting = 'Remote ID'
wm_RemoteDesktop = '{"width":1912.0,"height":1023.0,"offsetWidth":3.0,"offsetHeight":53.0,"isMaximized":false,"isFullscreen":false}'
draggablePositionMobile = '756.0,773.0'
showMobileActions = 'N'
wm_Terminal = '{"width":1912.0,"height":1023.0,"offsetWidth":3.0,"offsetHeight":53.0,"isMaximized":false,"isFullscreen":false}'
wm_Main = '{"width":null,"height":null,"offsetWidth":null,"offsetHeight":null,"isMaximized":true,"isFullscreen":false}'
remoteMenubarState = '{"pin":false}'
peer-tab-index = '0'
