-- Floating-terminal helper for external TUIs (lazygit).
-- Pure native: nvim_open_win + jobstart({ term = true }).

local M = {}

local function float_term(cmd, opts)
  opts = opts or {}
  local width = math.floor(vim.o.columns * (opts.scale or 0.9))
  local height = math.floor(vim.o.lines * (opts.scale or 0.9))
  local buf = vim.api.nvim_create_buf(false, true)
  local win = vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width = width,
    height = height,
    row = math.floor((vim.o.lines - height) / 2),
    col = math.floor((vim.o.columns - width) / 2),
    style = "minimal",
    border = "rounded",
    title = opts.title and (" " .. opts.title .. " ") or nil,
    title_pos = "center",
  })

  local job = vim.fn.jobstart(cmd, {
    term = true,
    env = opts.env,
    on_exit = function(_, code)
      if opts.on_exit then
        opts.on_exit(code)
      end
      if vim.api.nvim_win_is_valid(win) then
        vim.api.nvim_win_close(win, true)
      end
      if vim.api.nvim_buf_is_valid(buf) then
        pcall(vim.api.nvim_buf_delete, buf, { force = true })
      end
    end,
  })
  vim.cmd("startinsert")
  return job, buf, win
end

_G.FloatTerm = float_term

local function tool_command(name, bin, opts)
  vim.api.nvim_create_user_command(name, function()
    if vim.fn.executable(bin) == 0 then
      vim.notify(bin .. " is not installed", vim.log.levels.ERROR)
      return
    end
    float_term({ bin }, vim.tbl_extend("force", { title = bin }, opts or {}))
  end, { desc = "Open " .. bin .. " in a floating terminal" })
end

-- Lazygit nests an editor inside its own float when you open a file (`e`, or a
-- clicked delta hyperlink). We only want that redirect when lazygit is launched
-- from here, so rather than touch the user's lazygit config we merge a small
-- override on top of it via LG_CONFIG_FILE. The override hands editing back to
-- this nvim: quit lazygit, then `:tab drop` so the file lands in the main window
-- in a new tab -- or jumps to it if it is already open somewhere. `$NVIM` is set
-- automatically by nvim for the job.
local lazygit_edit_override = [[
# Generated by nvim (lua/term.lua); only applied to lazygit launched from nvim.
os:
  edit: 'nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote-send "<C-\><C-n>:tab drop {{filename}}<CR>"'
  editAtLine: 'nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote-send "<C-\><C-n>:tab drop {{filename}}<CR>:{{line}}<CR>"'
  editAtLineAndWait: 'nvim +{{line}} -- {{filename}}'
  openDirInEditor: 'nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote-send "<C-\><C-n>:tab drop {{dir}}<CR>"'
  editInTerminal: false
]]

local function lazygit_env()
  local files = {}

  -- LG_CONFIG_FILE replaces lazygit's own config discovery, so re-add the user's
  -- config first and let the override win on the keys it sets.
  local base = vim.env.XDG_CONFIG_HOME
  if not base or base == "" then
    base = vim.fs.joinpath(vim.env.HOME, ".config")
  end
  local user_cfg = vim.fs.joinpath(base, "lazygit", "config.yml")
  if vim.uv.fs_stat(user_cfg) then
    files[#files + 1] = user_cfg
  end

  local override = vim.fs.joinpath(vim.fn.stdpath("cache"), "lazygit-nvim-edit.yml")
  if pcall(vim.fn.writefile, vim.split(lazygit_edit_override, "\n"), override) then
    files[#files + 1] = override
  end

  if #files == 0 then
    return nil
  end
  return { LG_CONFIG_FILE = table.concat(files, ",") }
end

tool_command("Lazygit", "lazygit", { env = lazygit_env() })

vim.keymap.set("n", "<leader>gg", "<cmd>Lazygit<cr>", { desc = "Git: lazygit" })

return M
